version: "3.8"
services:
    gpsUtil:
      image: tourguide:gpsUtil
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "8080:8080"

    TripPricer:
      image: tourguide:tripPrice
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "8081:8081"

    RewardCentral:
      image: tourguide:rewardCentral
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "8082:8082"

networks:
  tourGuide-network:
